version: "3.8"

services:
  nextjs:
    build: .
    container_name: nextjs_app
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=andreisava.online,www.andreisava.online
      - LETSENCRYPT_HOST=andreisava.online,www.andreisava.online
      - LETSENCRYPT_EMAIL=savacristianandrei@yahoo.com
    expose:
      - "3000"
    networks:
      - proxy-network

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    restart: always
    environment:
      - DEFAULT_HOST=andreisava.online
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d:rw
      - ./html:/usr/share/nginx/html:rw
    networks:
      - proxy-network

  letsencrypt-companion:
    image: nginxproxy/acme-companion:latest
    container_name: nginx_proxy_le
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d:rw
      - ./html:/usr/share/nginx/html:rw
    environment:
      - NGINX_PROXY_CONTAINER=nginx_proxy
      - DEFAULT_EMAIL=savacristianandrei@yahoo.com
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
